### ISSUE TITLE
Cleaning :)

### ISSUE THREAD

**Issue by code34** [Aloee/oo_extdb2.Altis#1]
Hello Aloee,

i just clone the repo. First at all, i checked all files, and a lot are not part of oo_extdb2.

What do you think about to move them for a temporary reason, in /otherstuffs directory ?

**Comment by Aloee** [comment]
Okay, but first i try to remove all unnecessary only from the master branch, I hope it is possible.

**Comment by code34** [comment]
yes, just move them in other part, it can be usefull :)
