### ISSUE TITLE
Commit methods

### ISSUE THREAD

**Issue by code34** [Aloee/oo_extdb2.Altis#3]
how do you want to proceed for repositories commit ? :)

**Comment by Aloee** [comment]
"Dev" branch just for the view and my experience with git LOL.
I think we can use the "master" branch as a general, for stable pull and push worked code.
Now i burn time and an urgent need to do the work of 'modeling database' for my main project (armstalker). So now I'm planning to add to the class oo_extdb2 methods of reading and writing using SQL_CUSTOM_V2, SQL_RAW protocols and switch to other tasks.
extdb2 has other useful protocols, which will also be needed: MISC, LOG, STEAM_V2, RCON. I think these protocols not as unrelated and can be safely done by individual classes and commits to the "master" branch.

**Comment by code34** [comment]
i m agree with you :+1: 

in fact, for branch, i proceed this way : 

master is for already release code
branch version xxx is for current development

when all is done/ready, i merge the development branch to master
