### ISSUE TITLE
Collaborator list :)

### ISSUE THREAD

**Issue by code34** [Aloee/oo_extdb2.Altis#5]
Hi

Just to notify you, currently, i can t commit anything on the repo cause i m not in the collaborators list :)

**Comment by Aloee** [comment]
Oh sorry, I can not yet find how I can add you :)

**Comment by Aloee** [comment]
All OK you added. Now u collaborator )

**Comment by code34** [comment]
no worries ! :+1: 

it seems to work :dancer: Thanks !
