### ISSUE TITLE
just add a 0.1 branch

### ISSUE THREAD

**Issue by code34** [Aloee/oo_extdb2.Altis#6]
i just add a 0.1 branch to not overwrite your first commits :)

can you look it, im not sure all works, cause i develop from text editor without arma3 to test

i begin to chunck all the part of the constructor methods

**Comment by Aloee** [comment]
Excellent work , I wrote the code is too long and actually wrote a lot of excess. Please check the code through Arma, I have read it will see at least 5 syntactic typos on lines (88, 94, 98, 253, 257), and it must be quick merge in the master :)

**Comment by code34** [comment]
ok just done the commit :) just for my personnal information, how do you retrieve the typo problems ?

**Comment by Aloee** [comment]
read the code, just I have a built-in compiler in the head)

**Comment by code34** [comment]
lol thought you have a special tools :)
